# This is an empty template playbook
# You can write your custom configuration here

- name: disable qxl
  hosts:
    - routers
    - hosts
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: disable qxl
      include_role:
        name: disable-qxl
      when: ansible_os_family == 'Debian'


- name: user access
  hosts:
    - user_accessible_nodes
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: kypo-user-access
      kypo_user_access_password: 'kypo'


 


